const SET_PAGE = `SET_PAGE`,
	SET_MARKET = `SET_MARKET`,
	SET_SEARCH_FILTER = `SET_SEARCH_FILTER`,
	SET_DELTA_Y = `SET_DELTA_Y`,
	UPDATE_TIME = `UDPATE_TIME`,
	UPDATE_VIEWPORT = `UPDATE_VIEWPORT`,
	SWITCH_LIGHT_BULB = `SWITCH_LIGHT_BULB`;

export {
	SET_PAGE,
	SET_DELTA_Y,
	SET_SEARCH_FILTER,
	SET_MARKET,
	UPDATE_TIME,
	UPDATE_VIEWPORT,
	SWITCH_LIGHT_BULB,
};